### ISSUE TITLE
unstable_deferredUpdates was removed from react-dom

### ISSUE THREAD

**Issue by ashnur** [koba04/react-fiber-resources#22]
https://github.com/facebook/react/pull/13488

**Comment by koba04** [comment]
Yeah, I should update the documents, Thanks!

**Comment by koba04** [comment]
I've removed the mention of `unstable_deferredUpdates` from the README.md. Thank you!

**Comment by mqliutie** [comment]
What should I use now to instead of unstable_deferredUpdates

**Comment by ashnur** [comment]
@mqliutie https://reactjs.org/docs/hooks-reference.html#usetransition

**Comment by koba04** [comment]
I think the alternative is [useDeferredValue](https://reactjs.org/docs/hooks-reference.html#usedeferredvalue).
